// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using geocacheAPI.Models;

namespace geocacheAPI.Migrations
{
    [DbContext(typeof(geocacheAPIContext))]
    [Migration("20211122002527_geocacheInitial4")]
    partial class geocacheInitial4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("geocacheAPI.Models.Geocache", b =>
                {
                    b.Property<int>("GeocacheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Coordinate")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("GeocacheId");

                    b.ToTable("Geocaches");
                });

            modelBuilder.Entity("geocacheAPI.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EndDate")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("GeocacheId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("StartDate")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ItemId");

                    b.HasIndex("GeocacheId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("geocacheAPI.Models.Item", b =>
                {
                    b.HasOne("geocacheAPI.Models.Geocache", "Geocache")
                        .WithMany("Items")
                        .HasForeignKey("GeocacheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Geocache");
                });

            modelBuilder.Entity("geocacheAPI.Models.Geocache", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
